name: Vale Lint (Markdown Only)

on:
    pull_request:
      paths:
        - '**.md'

jobs:
    vale:
        name: Vale style check
        runs-on: ubuntu-latest
    
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:   
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4

            - name: Install Vale
              run: |
                  python -m pip install --upgrade pip
                  pip install vale
            
            - name: Get changed Markdown files
              id: changed_files
              run: |
                    git fetch origin ${{ github.base_ref }}
                    FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.md$' || true)
                    echo "Changed Markdown files:"
                    echo "$FILES"
                    echo "$FILES" > changed_files.txt
    
            - name: Run Vale
              if: always()  # Or add a better conditional check if needed
              run: |
                     if [ -f changed_files.txt ]; then
                     cat changed_files.txt | xargs -n 1 vale --config=en/.vale.ini --output=CLI || true
                     else
                     echo "No Markdown files to lint."
                     fi
            


                

             
    
    