name: Vale Lint (Changed Markdown Only)

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  vale:
    name: Vale style check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post PR comments
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Markdown files
        id: changed
        run: |
            git fetch origin ${{ github.event.pull_request.base.ref }}
            BASE_SHA=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
            git diff --name-only $BASE_SHA HEAD -- '*.md' > changed_files.txt
            echo "files=$(cat changed_files.txt | jq -R . | paste -sd, - | sed 's/^/[/;s/$/]/')" >> "$GITHUB_OUTPUT"

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
            files: ${{ steps.changed.outputs.files }}
            filter_mode: nofilter
            reporter: github-pr-check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
        