name: Vale Lint (Markdown Only)

on:
    pull_request:
      paths:
        - '**.md'

jobs:
    vale:
        name: Vale style check
        runs-on: ubuntu-latest
    
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.IAM_DOCS_GITHUB_BOT_TOKEN }}
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4

            - name: Install Vale
              run: |
                  python -m pip install --upgrade pip
                  pip install vale
            
            - name: Get changed Markdown files
              id: changed_files
              run: |
                  git fetch origin ${{ github.base_ref }}
                  FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.md$' || true)
                  echo "files=$FILES" >> "$GITHUB_OUTPUT"
            
            - name: Run Vale
              id: vale-lint
              if: steps.changed_files.outputs.files != ''
              run: |
                    echo "${{ steps.changed_files.outputs.files }}" | xargs -n 1 vale --config=.vale.ini --output=JSON > vale-output.json || true
              continue-on-error: true
            
            - name: No Markdown files changed
              if: ${{ steps.changed_files.outputs.files == '' }}
              run: echo "No Markdown files to lint."
            


                

             
    
    